const $=s=>document.querySelector(s); const BG=window.BinaryGame;
const tasks=[{n:37,o:[37,41,53,69]},{n:90,o:[74,90,82,106]},{n:165,o:[149,165,181,197]},{n:222,o:[214,220,222,238]},{n:255,o:[127,223,254,255]}];
const state={round:0,mistakes:0,hints:0,history:[],complete:false,revealed:false};
const tutor=BG.setupTutor({introKey:'level7',introMessage:'So geht das Spiel: Der Binärcode ist schon eingestellt. Addiere nur die Stellenwerte der leuchtenden Roboter und wähle unten die passende Zahl.',learningGoal:'Ein Kind dekodiert 8-Bit-Binärzahlen ins Dezimalsystem, indem es die Stellenwerte der gesetzten Bits addiert.',getFacts:()=>({code:BG.bitsFromNumber(tasks[state.round]?.n||0),correctNumber:tasks[state.round]?.n,round:state.round+1,mistakes:state.mistakes,revealed:state.revealed}),history:state.history,offlineReply:q=>{const l=q.toLowerCase();if(l.includes('dunkel'))return{message:'Nein. Dunkle Roboter stehen für 0 und tragen nichts zur Summe bei.',mood:'explaining'};return{message:'Addiere die Stellenwerte der leuchtenden Roboter. Genau diese Summe ist die gesuchte Dezimalzahl.',mood:'questioning'}}});
function renderDots(){ $('#roundDots').innerHTML=tasks.map((_,i)=>`<span class="round-dot ${i<state.round?'done':i===state.round&&!state.complete?'now':''}"></span>`).join('') }
function render(){const t=tasks[state.round]||tasks.at(-1),bits=BG.bitsFromNumber(t.n);BG.renderRobots($('#binaryRobots'),bits,{locked:true});$('#binaryString').textContent=BG.binaryString(bits);$('#sumText').textContent=state.revealed?BG.sumText(bits):'Die Rechnung bleibt zunächst verborgen.';$('#decodeChoices').innerHTML=t.o.map(n=>`<button class="decode-choice" data-answer="${n}">${n}</button>`).join('');$('#mistakeCount').textContent=state.mistakes;$('#roundLabel').textContent=`${Math.min(state.round+1,5)} von 5`;$('#progressBar').style.width=`${state.round/tasks.length*100}%`;renderDots();document.querySelectorAll('.decode-choice').forEach(b=>b.onclick=()=>choose(Number(b.dataset.answer),b))}
function choose(n,btn){if(state.complete)return;const correct=tasks[state.round].n;state.history.push({type:'answer',answer:n,correct:n===correct});if(n!==correct){state.mistakes++;$('#mistakeCount').textContent=state.mistakes;btn.classList.add('bad');setTimeout(()=>btn.classList.remove('bad'),450);tutor.say('Noch nicht. Zähle nur die Stellenwerte zusammen, deren Roboter leuchten.','questioning');return}btn.classList.add('good');tutor.say(`Richtig: Der Code steht für ${correct}.`,'success');setTimeout(()=>{state.round++;state.revealed=false;if(state.round>=tasks.length)finish();else render()},650)}
function stars(){if(state.mistakes===0&&state.hints===0)return 3;if(state.mistakes<=2)return 2;return 1}
function finish(){state.complete=true;$('#progressBar').style.width='100%';renderDots();const s=stars();$('#rewardStars').textContent='★'.repeat(s)+'☆'.repeat(3-s);$('#rewardText').textContent=s===3?'Alle fünf Codes ohne Fehler gelesen.':'Alle fünf Codes geknackt.';$('#rewardPanel').hidden=false;window.RoboProgress?.mark('level7',{completed:true,perfect:s===3,bestStars:s});tutor.say('Sehr gut! Du kannst fertige Binärcodes jetzt als Zahlen lesen.','success')}
function reset(){state.round=0;state.mistakes=0;state.hints=0;state.history.length=0;state.complete=false;state.revealed=false;$('#rewardPanel').hidden=true;render();tutor.say('Diesmal darfst du nichts umschalten. Lies den Code und finde seine Zahl.','greeting',{auto:false})}
$('#resetBtn').onclick=reset;$('#replayBtn').onclick=reset;$('#revealBtn').onclick=()=>{state.hints++;state.revealed=true;$('#sumText').textContent=BG.sumText(BG.bitsFromNumber(tasks[state.round].n));tutor.say('Hier siehst du die Rechenhilfe. Addiere genau diese leuchtenden Stellenwerte.','explaining')};$('#hintBtn').onclick=()=>{state.hints++;const bits=BG.bitsFromNumber(tasks[state.round].n),vals=bits.map((b,i)=>b?BG.WEIGHTS[i]:null).filter(Boolean);tutor.say(`Es leuchten ${vals.length} Roboter. Ihre Werte sind ${vals.join(', ')}.`,'thinking')};$('#explainBtn').onclick=()=>{state.hints++;tutor.say('Jede Stelle hat einen festen Wert. Leuchtet der Roboter, zählt dieser Wert mit. Ist er dunkel, zählt er 0.','explaining')};
reset();
