const $=s=>document.querySelector(s); const BG=window.BinaryGame; const message='ROBO'; const codes=[...message].map(c=>c.charCodeAt(0));
const state={round:0,mistakes:0,hints:0,history:[],complete:false,revealed:Array(4).fill(''),showValue:false};
const tutor=BG.setupTutor({introKey:'level8',introMessage:'So geht das Spiel: Lies das Byte zuerst als Zahl. Suche diese Zahl danach in der ASCII-Tabelle und klicke den passenden Buchstaben an. Vier Bytes ergeben die geheime Nachricht.',learningGoal:'Ein Kind versteht, dass ein Byte je nach vereinbartem Code ein Zeichen repräsentieren kann. Es dekodiert ASCII-Großbuchstaben über Bits → Zahl → Zeichen.',getFacts:()=>({byte:BG.bitsFromNumber(codes[state.round]||0),decimalValue:codes[state.round],round:state.round+1,revealedMessage:state.revealed.join(''),mistakes:state.mistakes,showValue:state.showValue}),history:state.history,offlineReply:q=>{const l=q.toLowerCase();if(l.includes('ascii'))return{message:'ASCII ist eine Zuordnung zwischen Zahlen und Zeichen. Großbuchstaben A bis Z haben dort die Werte 65 bis 90.',mood:'explaining'};if(l.includes('82')||l.includes('r'))return{message:'Der Buchstabe R hat im ASCII-Code den Zahlenwert 82. 82 wird binär als 01010010 gespeichert.',mood:'explaining'};return{message:'Erst liest du aus den acht Bits eine Zahl. Dann suchst du diese Zahl in der Zeichentabelle und bekommst den Buchstaben.',mood:'questioning'}}});
function buildAscii(){let html='';for(let n=65;n<=90;n++)html+=`<button type="button" class="ascii-cell ascii-choice" data-ascii="${n}" data-letter="${String.fromCharCode(n)}"><b>${String.fromCharCode(n)}</b>${n}</button>`;$('#asciiGrid').innerHTML=html}
function render(){const n=codes[state.round]||codes.at(-1),bits=BG.bitsFromNumber(n);BG.renderRobots($('#binaryRobots'),bits,{locked:true});$('#binaryString').textContent=BG.binaryString(bits);$('#sumText').textContent=state.showValue?BG.sumText(bits):'Berechne zuerst den Zahlenwert des Bytes.';$('#byteNumber').textContent=`${Math.min(state.round+1,4)} / 4`;$('#roundLabel').textContent=`${state.round} von 4`;$('#mistakeCount').textContent=state.mistakes;$('#progressBar').style.width=`${state.round/4*100}%`;$('#messageProgress').textContent=state.revealed.map(c=>c||'_').join(' ');$('#secretSlots').innerHTML=state.revealed.map((c,i)=>`<div class="secret-slot ${c?'revealed':''} ${i===state.round&&!state.complete?'current':''}">${c||'?'}</div>`).join('');document.querySelectorAll('.ascii-cell').forEach(c=>c.classList.toggle('highlight',state.showValue&&Number(c.dataset.ascii)===n))}
function submit(answer){if(state.complete)return;answer=String(answer||'').trim().toUpperCase();if(!answer)return;const correct=message[state.round];state.history.push({type:'letter',answer,correct:answer===correct});if(answer!==correct){state.mistakes++;render();const wrong=document.querySelector(`.ascii-choice[data-letter=\"${answer}\"]`);wrong?.classList.add('wrong');setTimeout(()=>wrong?.classList.remove('wrong'),420);tutor.say('Noch nicht. Berechne zuerst die Zahl des Bytes und klicke dann den passenden Buchstaben.','questioning');return}state.revealed[state.round]=correct;tutor.say(`Ja! Dieses Byte bedeutet ${correct}.`,'success');state.round++;state.showValue=false;if(state.round>=4){finish();return}render()}
function stars(){if(state.mistakes===0&&state.hints===0)return 3;if(state.mistakes<=2&&state.hints<=1)return 2;return 1}
function finish(){state.complete=true;$('#progressBar').style.width='100%';render();const s=stars();$('#rewardStars').textContent='★'.repeat(s)+'☆'.repeat(3-s);$('#rewardText').textContent=`Die Nachricht lautet: ${message}.`;$('#rewardPanel').hidden=false;window.RoboProgress?.mark('level8',{completed:true,perfect:s===3,bestStars:s});tutor.say(`Geschafft! Die geheime Nachricht lautet ${message}. Du hast aus Bits erst Zahlen und daraus Buchstaben gemacht.`,'success')}
function reset(){state.round=0;state.mistakes=0;state.hints=0;state.history.length=0;state.complete=false;state.revealed.fill('');state.showValue=false;$('#rewardPanel').hidden=true;buildAscii();render();tutor.say('Eine geheime Nachricht! Jeder Block aus acht Robotern steht diesmal für einen Buchstaben.','greeting',{auto:false})}
$('#asciiGrid').addEventListener('click',e=>{const btn=e.target.closest('.ascii-choice');if(btn)submit(btn.dataset.letter)});$('#resetBtn').onclick=reset;$('#replayBtn').onclick=reset;$('#revealBtn').onclick=()=>{state.hints++;state.showValue=true;render();tutor.say(`Der Zahlenwert dieses Bytes ist ${codes[state.round]}. Such diese Zahl jetzt in der Zeichentabelle.`,'explaining')};$('#hintBtn').onclick=()=>{state.hints++;if(!state.showValue){const bits=BG.bitsFromNumber(codes[state.round]);const vals=bits.map((b,i)=>b?BG.WEIGHTS[i]:null).filter(Boolean);tutor.say(`Addiere ${vals.join(' + ')}. Danach brauchst du nur noch die Zeichentabelle.`,'thinking')}else tutor.say(`Die Zahl ist ${codes[state.round]}. Schau in der Tabelle nach, welcher Großbuchstabe dazu gehört.`,'questioning')};$('#explainBtn').onclick=()=>{state.hints++;tutor.say('ASCII ist eine Tabelle: Zeichen bekommen feste Zahlen. Ein Byte speichert diese Zahl wieder als acht Nullen und Einsen.','explaining')};
reset();
