const $=s=>document.querySelector(s); const BG=window.BinaryGame; const targets=[13,86,173];
const state={round:0,bits:Array(8).fill(0),moves:0,hints:0,mistakes:0,history:[],complete:false};
const tutor=BG.setupTutor({introKey:'level6',introMessage:'So geht das Spiel: Jeder Roboter ist einen festen Stellenwert wert. Klick die passenden Roboter an, bis ihre Summe genau der Zielzahl entspricht. Leuchtend bedeutet 1, dunkel bedeutet 0.',learningGoal:'Ein Kind versteht das Binärsystem: acht Roboter stehen für die Stellenwerte 128 bis 1; an ist 1, aus ist 0; acht Bits bilden ein Byte.',getFacts:()=>({target:targets[state.round],bits:state.bits,currentValue:BG.numberFromBits(state.bits),weights:BG.WEIGHTS,round:state.round+1,moves:state.moves}),history:state.history,offlineReply:q=>{const l=q.toLowerCase();if(l.includes('128')||l.includes('links'))return{message:'Ganz links steht die höchste Stelle. Bei acht Bits ist ihr Wert 128, also 2 hoch 7.',mood:'explaining'};if(l.includes('byte'))return{message:'Acht Bits zusammen nennt man ein Byte. Mit acht Bits gibt es 256 verschiedene Muster.',mood:'explaining'};return{message:'Addiere nur die Werte der leuchtenden Roboter. Die dunklen Roboter zählen 0.',mood:'questioning'}}});
function minClicks(n){return BG.bitsFromNumber(n).reduce((a,b)=>a+b,0)}
const perfectClicks=targets.reduce((a,n)=>a+minClicks(n),0);
function renderDots(){ $('#roundDots').innerHTML=targets.map((_,i)=>`<span class="round-dot ${i<state.round?'done':i===state.round&&!state.complete?'now':''}"></span>`).join('') }
function render(){BG.renderRobots($('#binaryRobots'),state.bits);BG.setReadout(state.bits,$('#binaryString'),$('#sumText'),$('#decimalValue'));$('#targetNumber').textContent=targets[state.round]??targets.at(-1);$('#sideTarget').textContent=targets[state.round]??targets.at(-1);$('#roundLabel').textContent=`${Math.min(state.round+1,3)} von 3`;$('#moveCount').textContent=state.moves;$('#progressBar').style.width=`${Math.min(100,state.round/3*100)}%`;renderDots();bindBits()}
function bindBits(){document.querySelectorAll('.bit-robot').forEach(btn=>btn.addEventListener('click',()=>toggle(Number(btn.dataset.bit))))}
function toggle(i){if(state.complete)return;state.bits[i]=state.bits[i]?0:1;state.moves++;state.history.push({type:'toggle',bit:i,value:state.bits[i],current:BG.numberFromBits(state.bits)});render();const current=BG.numberFromBits(state.bits),target=targets[state.round];if(current===target){tutor.say(`Genau! ${target} ist geknackt.`,'success');setTimeout(nextRound,650)}else if(current>target){tutor.say(`Du bist bei ${current}. Das ist schon größer als ${target}. Vielleicht leuchtet ein zu großer Stellenwert.`,'thinking')}}
function nextRound(){state.round++;state.bits.fill(0);if(state.round>=targets.length){finish();return}render();tutor.say(`Nächster Code: Erzeuge jetzt die ${targets[state.round]}.`,'greeting')}
function stars(){if(state.moves===perfectClicks&&state.hints===0)return 3;if(state.moves<=perfectClicks+6)return 2;return 1}
function finish(){state.complete=true;$('#progressBar').style.width='100%';renderDots();const s=stars();$('#rewardStars').textContent='★'.repeat(s)+'☆'.repeat(3-s);$('#rewardText').textContent=s===3?`Perfekt: alle drei Zahlen mit genau ${perfectClicks} Schaltungen.`:`Du hast alle drei Zahlen erzeugt. Bestwert: ${perfectClicks} Schaltungen.`;$('#rewardPanel').hidden=false;window.RoboProgress?.mark('level6',{completed:true,perfect:s===3,bestStars:s,bestMoves:state.moves});tutor.say('Geschafft! Du kannst Zahlen jetzt mit acht leuchtenden oder dunklen Robotern codieren. Das ist ein Byte.','success')}
function reset(){state.round=0;state.bits.fill(0);state.moves=0;state.hints=0;state.mistakes=0;state.history.length=0;state.complete=false;$('#rewardPanel').hidden=true;render();tutor.say('Jeder leuchtende Roboter zählt seinen Wert dazu. Schaffst du zuerst die 13?','greeting',{auto:false})}
$('#resetBtn').onclick=reset;$('#replayBtn').onclick=reset;$('#hintBtn').onclick=()=>{state.hints++;const t=targets[state.round],needed=BG.bitsFromNumber(t);const wrong=state.bits.findIndex((v,i)=>v!==needed[i]);if(wrong>=0)tutor.say(`Schau auf den Stellenwert ${BG.WEIGHTS[wrong]}. Dieser Roboter müsste ${needed[wrong]?'leuchten':'dunkel sein'}.`,'questioning')};$('#explainBtn').onclick=()=>{state.hints++;tutor.say('Von links nach rechts sind die Stellen 128, 64, 32, 16, 8, 4, 2 und 1 wert. Addiere nur die Stellen, an denen der Roboter leuchtet.','explaining')};
reset();
